http://localhost:3000/users

###

POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "username": "lucas",
    "password": "donna"
}

###

GET http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "lucas",
    "password": "donna"
}

###

POST http://localhost:3000/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1Y2FzIiwicGFzc3dvcmQiOiIkMmIkMTAkY0Q2SzZid2N6ZWNVcEk3cmtmQUQvLno2eEx2c1E5bGNLMWhMWFZKYVJXSmQ0WnpDcE9kSC4iLCJpYXQiOjE2NzU1NzEzMDh9.Tcvf4V6r8Ew7fEUY6mbrKJxXMoqqWzFi0AapJ5wAUxg"
}

###

DELETE http://localhost:3000/users/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1Y2FzIiwicGFzc3dvcmQiOiIkMmIkMTAkY0Q2SzZid2N6ZWNVcEk3cmtmQUQvLno2eEx2c1E5bGNLMWhMWFZKYVJXSmQ0WnpDcE9kSC4iLCJpYXQiOjE2NzU1NzEyODV9.9n7Jro4M7HXk6XcSa5MS_Z8IJ26Hn7xOpTxPRGh_TpM"
}