http://localhost:3000/users

###

POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "username": "lucas",
    "password": "donna"
}

###

GET http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "lucas",
    "password": "donna"
}

###

POST http://localhost:3000/users/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1Y2FzIiwicGFzc3dvcmQiOiIkMmIkMTAkY0Q2SzZid2N6ZWNVcEk3cmtmQUQvLno2eEx2c1E5bGNLMWhMWFZKYVJXSmQ0WnpDcE9kSC4iLCJpYXQiOjE2NzU1NzEzMDh9.Tcvf4V6r8Ew7fEUY6mbrKJxXMoqqWzFi0AapJ5wAUxg"
}

###

DELETE http://localhost:3000/users/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1Y2FzIiwicGFzc3dvcmQiOiIkMmIkMTAkY0Q2SzZid2N6ZWNVcEk3cmtmQUQvLno2eEx2c1E5bGNLMWhMWFZKYVJXSmQ0WnpDcE9kSC4iLCJpYXQiOjE2NzU1NzEyODV9.9n7Jro4M7HXk6XcSa5MS_Z8IJ26Hn7xOpTxPRGh_TpM"
}

###

POST http://localhost:3000/venues/create
Content-Type: application/json

{
    "name": "First Venue",
    "hosts": ["63e59d905971a34a76dd9721", "63e59d625971a34a76dd9720", "63e5963e5971a34a76dd971c"]
}

###

PATCH http://localhost:3000/venues/63e3c0445683b5a4924d8880
Content-Type: application/json

{
    "name": "First Venue",
    "description": "Party 3",
    "isPublic": true
}

###

GET http://localhost:3000/hosts/63e296566e0fcb0d849b6d1d
Content-Type: application/json

###

DELETE http://localhost:3000/venues/63e5a9c3b00dfcef832fbe20

###

GET http://localhost:3000/venues/63e3c0445683b5a4924d8880


###

PATCH http://localhost:3000/venues/addHost/63e5a754ec232ee52572afd5
Content-Type: application/json

{
    "hosts": ["63e5963e5971a34a76dd971c"] 
}

###

PATCH http://localhost:3000/venues/removeHost/63e5a754ec232ee52572afd5
Content-Type: application/json

{
    "hosts": ["63e5963e5971a34a76dd971c"] 
}